# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(2)(432d78af-ba15-406c-a213-c101f8b2261f)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'dotnet publish --output $(Build.ArtifactStagingDirectory)'
